# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

target 'OpenGL_ES_Filter' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'Masonry'
  # Pods for OpenGL_ES_Filter

end
